### ISSUE TITLE
Need help finding onmt_path

### ISSUE THREAD

**Issue by Kenan-jeff-Jiang** [asahala/BabyLemmatizer#1]
Thanks for this amazing work!!!

I followed the readme and installed Opennmt in a virtual env, I am trying to set the onmt_path, but the 
OpenNMT/lib/python3.9/site-packages does not have a onmt folder. Attaching a screenshot of my sight-packages folder.
<img width="1147" alt="Screenshot 2024-03-22 at 8 50 39 PM" src="https://github.com/asahala/BabyLemmatizer/assets/145389133/dfd35219-6909-4e24-9a86-bd3110d18505">
Please let me know if there is anything I should try or I have overlooked, thanks in advance!

**Comment by asahala** [comment]
onmt_path should point to the path where OpenNMT has files **train.py** and **build_vocab.py**.

**Comment by Kenan-jeff-Jiang** [comment]
> onmt_path should point to the path where OpenNMT has files **train.py** and **build_vocab.py**.

Thank you for your support, I have solved my problem following your guidence.
